name: hedgehog

proxy:
  hedgehog:
    - hedgehog.lndo.site

services:
  # PostgreSQL
  db:
    type: postgres
    portforward: 5432
    creds:
      user: hh
      password: hh
      database: hh

  # HedgeHog GraphQL server
  hedgehog:
    type: node
    build_as_root:
      - build-scripts/root.sh
    build:
      - build-scripts/me.sh
    command: yarn start
    run:
      - node commands/schema.js --enable-uuid
      - yarn command:schema
      - yarn command:seed --authors 10 --metas 10 --media 10
    overrides:
      image: node:10
      depends_on:
        - db
      volumes:
        - "/app/node_modules"
        - "/app/run"
      environment:
        NODE_ENV: "development"
        # echo '{"pg":[{"username":"postgres","password":"","host":"db","query":{"is_master":true},"path":"hh","scheme":"public","port":5432}]}' | base64
        PLATFORM_RELATIONSHIPS: "eyJwZyI6W3sidXNlcm5hbWUiOiJwb3N0Z3JlcyIsInBhc3N3b3JkIjoiIiwiaG9zdCI6ImRiIiwicXVlcnkiOnsiaXNfbWFzdGVyIjp0cnVlfSwicGF0aCI6ImhoIiwic2NoZW1lIjoicHVibGljIiwicG9ydCI6NTQzMn1dfQo="
        # GraphQL endpoint used by integration tests.
        INTEGRATION_ENV_URL: "http://hedgehog/graphql"
        # Service port.
        PORT: 80

tooling:
  yarn:
    service: hedgehog
    cmd: yarn
    description: Run yarn commands inside hedgehog
