name: hedgehog

proxy:
  hedgehog:
    - hedgehog.lndo.site

services:
  # PostgreSQL
  db:
    type: postgres
    portforward: 5432
    creds:
      user: hh
      password: hh
      database: hh

  # HedgeHog GraphQL server
  hedgehog:
    type: node
    install_dependencies_as_root:
      - apt-get update
      - apt-get install -y postgresql-client
      - apt-get install -y sudo
      - adduser www-data sudo
      - echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
    install_dependencies_as_me:
      - npm i -g yarn
      - yarn global add pm2@latest
      - yarn install
    command: yarn start
    run:
      - node commands/schema.js --enable-uuid
      - yarn command:schema
      - yarn command:seed --authors 10 --metas 10 --media 10
    overrides:
      services:
        image: node:10
        depends_on:
          - db
        volumes:
          - "/app/node_modules"
          - "/app/run"
        environment:
          NODE_ENV: "development"
          # echo '{"pg":[{"username":"hh","password":"hh","host":"db","query":{"is_master":true},"path":"hh","scheme":"public","port":5432}]}' | base64
          PLATFORM_RELATIONSHIPS: "eyJwZyI6W3sidXNlcm5hbWUiOiJoaCIsInBhc3N3b3JkIjoiaGgiLCJob3N0IjoiZGIiLCJxdWVyeSI6eyJpc19tYXN0ZXIiOnRydWV9LCJwYXRoIjoiaGgiLCJzY2hlbWUiOiJwdWJsaWMiLCJwb3J0Ijo1NDMyfV19Cg=="
          # GraphQL endpoint used by integration tests.
          INTEGRATION_ENV_URL: "http://hedgehog/graphql"
          # Service port.
          PORT: 80

tooling:
  yarn:
    service: hedgehog
    cmd: yarn
    description: Run yarn commands inside hedgehog
